name: Check action changes

on:
  pull_request:
    paths:
      - .github/workflows/update.yml
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: npm
          cache-dependency-path: _scripts/package-lock.json
      - run: npm ci
        working-directory: _scripts
      - run: node _scripts/check-action.mjs
